title: Local Land Charges Programme
description: >- 
  Documentation repositroy for the Local Land Charges Programe
baseurl: "/local-land-charge"
url: "https://landregistry.github.io/"

# Build settings
theme: govuk-jekyll-theme
remote_theme: frankieroberto/govuk-jekyll-theme
plugins:
  - jekyll-feed
