# config.yml

backend:
  name: github
  repo: Louis331/Louis331.github.io
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/images/uploads'
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Page" # Used in the UI
    folder: "_docs/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Type", name: "type", widget: "hidden", default: "article"}
      - {label: "Published", name: "published", widget: "hidden", default: "true"}
      - {label: "Status", name: "status", widget: "hidden", default: "publish"}
      - {label: "Body", name: "body", widget: "markdown"}